export default {
  mongoConnection: process.env.MONGO || "mongodb://127.0.0.1:27017",
  dbName: process.env.DB || "fia",
  fetchInterval: parseInt(process.env.FETCH ?? "60"),
  s3Access: process.env.S3ACCESS,
  s3Secret: process.env.S3SECRET,
  s3Endpoint: process.env.S3ENDPOINT,
  s3Bucket: process.env.S3BUCKET,
  pageConf: {
    "Provisional Starting Grid": 2,
    "Final Qualifying Classification": 2,
    "Circuit Map": 2,
    "Provisional Qualifying Classification": 2,
    "Qualifying deleted lap time - Double Yellow": 2,
    "P3 Classification": 2,
    "Race Directors Note - Post Qualifying Procedure": 2,
    "New PU elements for this Event": 2,
    "P2 deleted lap times - Double Yellow": 2,
    "P1 Classification": 2,
    "Entry List": 2,
    "PU elements used per driver up to now": 2,
    "Championship Points": 2,
    "Final Race Classification": 2,
    "Provisional Race Classification": 2,
    "Final Starting Grid": 2,
    "Race Directors Note - Post Race Procedure": 2,
    "Race Directors Note - Pre-Race Procedure": 2,
  },
};
